<?php
/**
 * One-time schema extractor.
 * Runs standalone (no prior PDO connection), dumps schema for the tables we need,
 * strips FK constraints, and prints the PHP array literal to embed in the test.
 */
set_time_limit(30);

$mysqldump = 'C:\\xampp\\mysql\\bin\\mysqldump.exe';

$tables = [
    'roles','accounts','financial_years','accounting_periods',
    'users','members','loan_applications',
    'loan_types','loan_product_settings','loan_product_rules','loan_interest_brackets',
    'journal_number_sequences','journal_entries','journal_lines','journal_entry_audit',
    'loans','loan_installments','loan_repayments','loan_penalties',
    'loan_weekly_interest','loan_weekly_savings',
    'business_loan_interest_payments','business_loan_weekly_savings',
    'member_savings_accounts','savings','activity_logs','notifications','member_fees',
    // Note: 'fees' excluded — its InnoDB tablespace is corrupted (known SA-3 finding)
    // and mysqldump hangs on it. The fees table DDL is seeded separately via INSERT.
];

$schemas = [];
foreach ($tables as $t) {
    // Each call is a fresh, short-lived process — no PDO connection held open
    $desc = [0 => ['pipe','r'], 1 => ['pipe','w'], 2 => ['pipe','w']];
    $argv = [$mysqldump, '--no-defaults', '-h', '127.0.0.1', '-P', '3306', '-u', 'root',
             '--no-data', '--skip-lock-tables', '--compact', 'empower_db', $t];
    $proc = proc_open($argv, $desc, $pipes);
    fclose($pipes[0]);
    $out = stream_get_contents($pipes[1]);
    $err = stream_get_contents($pipes[2]);
    fclose($pipes[1]); fclose($pipes[2]);
    $rc  = proc_close($proc);

    if ($rc !== 0 || strlen(trim($out)) < 20) {
        fwrite(STDERR, "SKIP {$t}: rc={$rc} err=" . substr($err,0,80) . "\n");
        continue;
    }
    // Strip FK constraints
    $clean = preg_replace(
        '/,\s*CONSTRAINT\s+`[^`]+`\s+FOREIGN\s+KEY\s+\([^)]+\)\s+REFERENCES\s+`[^`]+`\s*\([^)]+\)(?:\s+ON\s+(?:DELETE|UPDATE)\s+\w+(?:\s+\w+)?){0,2}/i',
        '', $out
    );
    // Extract just the CREATE TABLE statement
    if (preg_match('/(CREATE TABLE.*?ENGINE=[^\n]+)/s', $clean, $m)) {
        $schemas[$t] = $m[1];
        fwrite(STDERR, "OK: {$t}\n");
    }
}

// Output as a PHP file
echo "<?php\n";
echo "// AUTO-GENERATED by _extract_schema.php — do not edit manually\n";
echo "// Run: php tests/_extract_schema.php > tests/_schema_cache.php\n";
echo "return [\n";
foreach ($schemas as $t => $sql) {
    echo "    " . var_export($t, true) . " => " . var_export($sql, true) . ",\n";
}
echo "];\n";
