-- Shares Module — Stage 4-A (Reporting/Reference Prerequisite Remediation, 2026-09).
-- Purely additive. Nothing existing is altered, renamed, or removed.
--
-- 1) external_reference: a dedicated field for a future staff-entered
--    real-world reference (Mobile Money transaction ID, bank reference,
--    receipt/cheque number), matching the existing convention already used
--    by savings/other_income_transactions/expenses/loan_repayments (each
--    keeps reference_number VARCHAR(100) for the external value, separate
--    from an internal sequence field). share_transactions.reference_number
--    remains VARCHAR(20) and remains the INTERNAL reference field already
--    used by Stage 2 (the withdrawal's own WDL-######) and Stage 3 (the
--    "Opening — ..." labels) -- it is NOT renamed, resized, or repurposed
--    here. No UI is added for this column in this stage.
--
-- 2) SHR sequence row: reserves the prefix for a future current-transaction
--    reference generator to use via the existing, proven-safe
--    `SELECT last_number FROM journal_number_sequences WHERE prefix=? FOR
--    UPDATE` pattern already used by 22 other prefixes. No SHR-###### is
--    generated by this stage.

ALTER TABLE `share_transactions`
    ADD COLUMN `external_reference` VARCHAR(100) NULL
        COMMENT 'Staff-entered real-world reference (Mobile Money/bank/receipt/cheque) for a future current-transaction write path -- distinct from reference_number, which is the internal WDL-###### / "Opening -- ..." field used by Stages 2-3'
        AFTER `reference_number`;

INSERT INTO `journal_number_sequences` (`prefix`, `last_number`)
SELECT 'SHR', 0
WHERE NOT EXISTS (SELECT 1 FROM `journal_number_sequences` WHERE `prefix` = 'SHR');
